version: "3.9"

services:
  postgres-db:
    container_name: garanto-container
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: garanto
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5003:5432
    restart: on-failure